services:
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: cineplexx_worker
    env_file:
      - ./app/.env
    volumes:
      - rss_out:/out
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: cineplexx_nginx
    depends_on:
      - worker
    ports:
      - "8080:80"
    volumes:
      - rss_out:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  rss_out: